name: DAST

on:
  workflow_dispatch:

jobs:
  dast:
    name: Local Deploy + DAST Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build app Docker image
        run: docker build -t my-temp-app .

      - name: Run app in Docker (port 3000)
        run: docker run -d --name app -p 3000:3000 my-temp-app

      - name: Wait for app to be ready
        run: |
          echo "Waiting for app to become healthy..."
          for i in {1..15}; do
            curl -s http://localhost:3000 && break || sleep 2
          done

      - name: Run Nmap DAST scan
        run: |
          docker pull hysnsec/nmap
          docker run --rm -v ${{ github.workspace }}:/tmp hysnsec/nmap \
            -Pn http://host.docker.internal:3000 -oX /tmp/nmap-output.xml || true
            
      - name: Upload Nmap Report
        uses: actions/upload-artifact@v4
        with:
          name: dast-nmap-report
          path: |
            nmap-report.xml
            nmap-report.txt
