name: Python SAST Scan - Bandit

on:
  workflow_dispatch:

jobs:
  bandit-scan:
    name: Bandita
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit scan (non-blocking)
        run: |
          bandit -r . -f txt -o bandit-report.txt || true
          echo "_bandit_report_"
          cat bandit-report.txt

      - name: Upload Bandit report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit-report.txt
