name: Push 

on:
  workflow_dispatch:

jobs:
  push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t myapp .

      - name: Tag Docker image for GHCR
        run: |
          IMAGE_NAME=ghcr.io/${{ github.push }}/myapp:latest
          docker tag myapp $IMAGE_NAME

      - name: Push Docker image to GHCR
        run: |
          IMAGE_NAME=ghcr.io/${{ github.push }}/myapp:latest
          docker push $IMAGE_NAME
