name: Trivy Image Scan

on:
  workflow_dispatch:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: dbname
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U user"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image (bez pusha)
        run: docker build -t myapp:latest .

      - name: Run container with DB connection
        run: |
          docker run -d --name myapp \
            -e DATABASE_URL=postgres://user:pass@localhost:5432/dbname \
            myapp:latest

      - name: Wait for DB to be ready
        run: sleep 15

      - name: Run Django migrations
        run: docker exec myapp python /app/manage.py migrate

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install wget -y
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.51.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.51.1_Linux-64bit.deb

      - name: Run Trivy image scan (HTML report)
        run: |
          mkdir -p trivy-reports
          trivy image --format template --template "@/usr/local/share/trivy/templates/html.tpl" \
            --output trivy-reports/report.html \
            --severity HIGH,CRITICAL myapp:latest

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-html-report
          path: trivy-reports/report.html

      - name: Cleanup container
        run: |
          docker stop myapp
          docker rm myapp
