name: DAST Nikto

on:
  workflow_dispatch:

jobs:
  dast:
    runs-on: ubuntu-latest
    name: Run Nikto DAST scan

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image for app
        run: docker build -t my-temp-app .

      - name: Run app container (localhost:8000)
        run: docker run -d --name app -p 8000:8000 my-temp-app

      - name: Wait for app to be ready
        run: |
          echo "Waiting for app to respond..."
          for i in {1..15}; do
            curl -s http://localhost:8000 && break || sleep 2
          done

      - name: Run Nikto scan
        run: |
          mkdir nikto-reports
          docker run --rm --network=host -v $(pwd)/nikto-reports:/nikto \
            alpine:3.19 sh -c "
              apk add --no-cache perl wget unzip git &&
              git clone https://github.com/sullo/nikto.git /nikto-src &&
              cd /nikto-src/program &&
              perl nikto.pl -h http://localhost:8000 \
                            -o /nikto/nikto-report.html -Format html &&
              perl nikto.pl -h http://localhost:8000 \
                            -o /nikto/nikto-report.txt -Format txt
            "

      - name: Upload Nikto reports
        uses: actions/upload-artifact@v4
        with:
          name: nikto-dast-report
          path: nikto-reports/
