name: Python Security Audit

on:
  workflow_dispatch:

jobs:
  pip-audit:
    name: SCA_pierwszy_scan_pip-audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install pip-audit
        run: pip install pip-audit

      - name: Run pip-audit (non-blocking, log to file)
        run: |
          pip-audit > audit-report.txt || true
          echo "_pip-audit_report_"
          cat audit-report.txt

      - name: Upload audit report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pip-audit-report
          path: audit-report.txt
