name: Temporary DAST Deployment

on:
  workflow_dispatch:

jobs:
  dast-temp-deploy:
    name: apka w Dockerze (DinD-ready for DAST)
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        privileged: true
        options: >-
          --dns 8.8.8.8
          --name docker
        ports:
          - 2375:2375

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker CLI
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t my-temp-app .

      - name: Run Docker container (port 8001)
        run: |
          docker run -d --name temp-app -p 8001:8000 my-temp-app
          echo "Waiting for app to become healthy..."
          for i in {1..30}; do
            curl -sSf http://localhost:8001 && break || sleep 2
          done

      - name: Check if app is running
        run: curl -v http://localhost:8001 || (echo "App failed to start!" && exit 1)

      - name: Run OWASP ZAP baseline scan
        run: |
          docker run --network host -v $(pwd):/zap/wrk ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
            -t http://localhost:8001 \
            -r zap-report.html || true

      - name: Upload ZAP report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-report.html
